# 繁殖
ヤクシマザルの初産年齢は大方6歳で、2～3年おきに寿命近くまで子供を産む[@fujita2008]。

## 季節繁殖性
ニホンザルは、はっきりした季節繁殖性 (breeding seasonality)を示す [@bercovitch_harvey2004;@fujita2010]。そのため、交尾期となる秋・冬から約180日の妊娠期間を経て、春から初夏に出産する。


### サルが春に生まれるのはなんで？
ニホンザルは季節繁殖性のため、ヒトのアカンボウが一年を通して生まれてくるのとはちがい、春から夏までの数か月に集中してアカンボウが生まれる [@fooden_aimi2003]。これは日長や室温などの季節変化が乏しい室内飼育であっても変わらない。

### 交尾期のオス
オスはどのような社会的立ち位置であっても必ずメスと交尾できるわけではない。<br>
第一位オス（アルファオス）は採食や休息の時間を削ってでも狙っているメスがほかのオスと交尾しないように防衛 (mate guarding) する高コストな戦術をとる。一方で、低順位オスは交尾回数と採食量に違いはなく低コスト戦術をとる[@matsubara2003]。これのオスの交尾戦術のちがいは、おそらくオスの生活史と高い社会性比に伴う群れ形成に関連すると考えられている。

社会性比
: socionomic sex ratio。繁殖可能なオスとメスの比率。ヤクシマザルはホンドザルと比べて群れ内にいるオスの数が多く、オス/メスの比率が高い。

## 妊娠
妊娠期間は約6か月（173±7日）であることが知られており[@nigi1976]、受胎月は9月から2月に限られる。

## 出産
### 出産のタイミング
出産のほとんどは夜に行われる。これはヒト以外の霊長類でも確認されている @brandt_mitchell1971^,^@douglas2014^,^@goodlin_sackett1983^,^@price2016^,^@suzuki1990。それには以下の理由が考えられている。

1. 集団が移動しない夜間に出産することでアカンボウの世話や休息を十分にとれる
1. 群れ内の個体からの干渉が抑制される
1. 外敵に襲われることが少ない

### 難産なニホンザル
ニホンザルでは、新生児の頭骨が母親の産道に占める割合である頭骨骨盤比率（cephalopelvic proportion）が、ヒトと同等かそれ以上である @rosenberg_trevathan2002^,^@moffett2017^,^@moffett2021 ことから、霊長類の中でも難産であることが知られている。ヒトが難産である理由として、ヒトの骨盤の大きさには二足歩行のしやすさと出産のしやすさの間にトレードオフがあることが知られており、「産科学のジレンマ（obstetrical dilemma）」と呼ばれている。しかし、四足歩行の霊長類でもこのジレンマがあるのかどうかはわかっていないが、骨盤の形が継続的に変化することが報告されており[@morimoto2023]、産科学的リスクを軽減している可能性が示唆されている。。



