# はじめに
この文章はニホンザルのことを紹介しつつ、その亜種であるヤクシマザルのことを知ることを目的としています。そのため、まずニホンザル一般の話から始め、それと対比しつつヤクシマザルの特徴について紹介することを基本スタイルとします。<br>
さらに文献を調べて知識を深めたい人向けに、キーワードとなる専門用語については英語を括弧で書きました。文章の肩に振ってある数字は文末の引用文献番号と対応しています。

ニホンザル
: ニホンザルは青森県から鹿児島県本土までに生息しているホンドザル（学名：*Macaca fuscata fuscata*）と屋久島に生息しているヤクシマザル（学名：*Macaca fuscata yakui*）の2亜種に分けられる。

---

**¡注意!**<br>
この文章は筆者がヤクシマザルを中心にニホンザルについてまとめたものですが、第三者による査読を受けていません。筆者は情報について正確に書くように努めていますが、間違いがある可能性もあるのでご注意ください。引用する場合は、各自責任をもって原典に当たって確認してください。


# ニホンザルの体のふしぎ
ニホンザルには、ヒトにはない体の構造がみられる。<br>
これらの構造はニホンザルにとってどのような意味があるのだろうか？




<!-- ## 拇指対向性 -->

## 顔が大きくなるのはなんで？
ニホンザルは「**頬袋**」をもっている [@maruhashi1993]。<br>
この頬袋があるおかげで「ながら食い」ができる。<br>
ニホンザルの仲間であるオナガザル上科のサル（旧称：旧世界ザル）は、オマキザル上科のサル（旧称：新世界ザル）や類人猿とはちがい、頬袋をもっている。この頬袋によって、果実を丸呑みするだけでなく、一時保存することもできる。一時保存できることで、移動や毛づくろいをしながら頬袋に貯めた果実を食べている。

この頬袋があることで種子散布の距離が変わるため [@yumoto1998]、植物にとっても無視できない重要な部位である。

<!-- 頬袋は未熟果の消化するために発達したのか？ -->
<!-- 未熟果を嘔吐せずに採食するため？？ -->

<!-- 旧称にするべき理由 -->
<!-- 中村さんの2021年11月12日の特論を参照 -->

<!-- 系統樹を入れる -->

## お尻にあるコブは何？
ニホンザルは「**尻ダコ**」と呼ばれる突起物がある。<br>
尻ダコは、オナガザル科と類人猿のテナガザル科の霊長類の坐骨結節に付着し，坐ることへの適応を高めていると考えられている [@washburn1957]。<br>
オナガザル科に属するニホンザルは、この尻ダコをクッションとして使えるおかげで、長いこと座っていられる。

<!-- # ヤクシマザルのふしぎ -->
<!-- ## 他の地域のニホンザルより体が小さいのはなんで？ -->
<!-- 身体が小さい理由は明らかにされていないが、仮説は二つある。 -->

<!-- 1. **島嶼効果（とうしょこうか）** -->
<!-- 2. **ベルクマンの法則** -->

<!-- 島嶼効果が働いている可能性がある。島嶼効果は俗にフォスターの法則とも呼ばれている。 -->

# 発達
<!-- スプレイグさん、川添さんのD論を参照 -->

## アカンボウ期
本土のニホンザルはオスのアカンボウの方がメスよりも母親から離れようとするのが早く、生後1週間ほどで見られる [@hasegawa1983]。

## コドモ期
- ３歳を過ぎる頃から、メスは母親と近接する時間が長く、弟や妹の子守り行動が多いがほかのコドモとの遊ぶ時間は減る。一方で、オスのコドモは遊びの時間はあまり変わらず、母親との近接時間が減少し[@mori_naito1986;@nakamichi1989]、群れ周辺にいるオスたちとの交渉をもち始める [@mori_naito1986]。屋久島での発達についての詳しい研究はないが、ほぼ同様の傾向がみられる [@furuichi2000]。

<!--  **＠幸島**:--> 
- オスは同年齢のオスとよく近接し、メスは年下個体と交渉している傾向がある[@hayaki1983]。 

## ニホンザルのオスの移出
移出 (dispersal) 
: 群れから出ていくこと。ニホンザルでは、オスが性成熟する前に自分が生まれ育った出自群を出て、メスは基本的に出自群で一生を過ごす @nishida1966^,^ @sugiyama1976^,^ @sprague1998。


- 出自群からの移出である出自分散 (natal dispersal) について金華山と屋久島で比較した研究では [@sprague1998]、平均年齢で屋久島が5.3歳（3.5-10.5歳）、金華山が4.7歳（3-9歳）であった。金華山については別の報告[@sugiura_koyama2002]でも同様の傾向（平均値・中央値ともに５歳、3-9歳）であり、4-6歳で移出する割合が全体の92%を占める。

### ヤクシマザルのオスの移出

屋久島ではオスの分散は交尾期に集中しており、これは屋久島では群れ同士が隣接しあっているためとされる [@sprague1992]

# 群れ
## 分布域・個体数　　
ニホンザル（*Macaca fuscata*）の分布域は、最北を下北半島、南限を屋久島にしている。<br>
現生霊長類で最北限に生息していることで知られている。

### ヤクシマザルの分布・個体数
@hanya2020 , @miyata2017 を参考に情報を整理。

- 1993年、1994年に行われた広域調査では、屋久島全体の25％に当たる海岸から1-2kmの距離にある127km^2^の調査域内に、131群、1984-3850頭が生息していると推定された [@yoshihiro1998]。

そのほかの調査では[@hanya2000]、<br>

- 自然林が最も残っている西部海岸域： 60～100頭/km^2^で、これは野生ニホンザルで最大

- そのほかの海岸域：5～20頭/km^2^、植林による植生の攪乱、捕獲の影響があると考えられる。

- 標高300m以上：20～40頭/km^2^、照葉樹林帯に生息するホンドザルの密度と同程度かむしろ少ない。

### 遊動域
遊動域とは、群れが移動する範囲のことをさす。行動圏ともいう。

- 屋久島低地での群れ遊動域：約数十ヘクタール（約0.2-0.3km^2^）[@kurihara_hanya2015]
- 遊動域の約50％は他群と重複しており [@maruhashi1998]、群れの密度は4.8群/km^2^あるとされる [@yamagiwa_hill1998;@yoshihiro1999]。

- 採食量は均一な森において遊動域($R$)に直接的に比例すると思われるため、群れサイズ($P$)は遊動域に直接的に比例すると思われる。遊動域と群れサイズについて調べた研究では、$R=1.84P$の関係式であらわされた[@maruhashi1982]。

## 群れの構成
複数のオトナのオスと複数のオトナのメス、そのコドモたちからなる**複雄複雌群（multi-male and multi-female groups）**を形成する [@yamagiwa2010]。ニホンザルの社会では、メスは出自の群れで一生を過ごし、オスはほかの群れで過ごすようになる。このような社会は**母系社会（maternal society）**と呼ばれている。オスは3歳頃から他の群れに移籍することが知られ [@sprague1998]、何年かするとまた別の群れに移籍することを繰り返す。<br>

しかし、出自の群れを移籍したオスを死ぬまで追い続けることは非常に難しく、わかっていないことがまだまだ多い。

# 遺伝的観点
## 種内変異
- ミトコンドリアDNAで調べた結果、ヤクシマザルは九州のニホンザルよりも遺伝的多様性が低い [@hayaishi_kawamoto2006]。
   - 屋久島の個体群は急拡大したことを示唆
   - 個体群の急拡大は7300年前の[喜界カルデラ](https://ja.wikipedia.org/wiki/%E9%AC%BC%E7%95%8C%E3%82%AB%E3%83%AB%E3%83%87%E3%83%A9)の噴火によるボトルネック効果と関連している可能性
   - ハプロタイプの多様性に高度分布の偏りがみられ、植生回復の影響が考えられる

**喜界カルデラの噴火**：人類史上最も大きな噴火とされる。噴火による津波の到来が小瀬田の地層から確認されている [@nanayama_maeno2018]

## 系統発生
### 属レベルでの観点
ニホンザルが含まれているグループであるマカク属は約20種いて、北西アフリカに生息するバーバリーマカク（*Macaca sylvanus*）以外はすべてアジア南部に生息している。マカク属は700～800万年前のアフリカ北部を起源とし、500～600万年前に中近東を経てユーラシア大陸へ進出した[@hamada2008]。

### ニホンザルの祖先
ニホンザルの祖先は、少なくとも43～63万年前までに朝鮮半島を経て大陸から移動してきたと考えられている[@aimi2002]。これは日本人の祖先が日本列島にやってきた時代よりはるか昔のことである。
その後、海水面の上昇により大陸と隔離し、温暖化とともに日本列島各地に広がったと考えられている。

屋久島はニホンザルが生息する南限で、ここに生息するニホンザルは最も早く他地域と隔離され、別亜種のヤクシマザル（*Macaca fuscata yakui*)に分類されている。

# 繁殖
ヤクシマザルの初産年齢は大方6歳で、2～3年おきに寿命近くまで子供を産む[@fujita2008]。

## 季節繁殖性
ニホンザルは、はっきりした季節繁殖性 (breeding seasonality)を示す [@bercovitch_harvey2004;@fujita2010]。

### サルが春に生まれるのはなんで？
ニホンザルは季節繁殖性のため、ヒトのアカンボウが一年を通して生まれてくるのとはちがい、春から夏までの数か月に集中してアカンボウが生まれる [@fooden_aimi2003]。

<!-- なぜニホンザルは季節繁殖性なのか？ -->
<!-- それは -->


### 交尾期のオス
オスはどのような社会的立ち位置であっても必ずメスと交尾できるわけではない。<br>
第一位オス（アルファオス）は採食や休息の時間を削ってでも狙っているメスがほかのオスと交尾しないように防衛 (mate guarding) する高コストな戦術をとる。一方で、低順位オスは交尾回数と採食量に違いはなく低コスト戦術をとる[@matsubara2003]。これのオスの交尾戦術のちがいは、おそらくオスの生活史と高い社会性比に伴う群れ形成に関連すると考えられている。

社会性比
: socionomic sex ratio。繁殖可能なオスとメスの比率。ヤクシマザルはホンドザルと比べて群れ内にいるオスの数が多く、オス/メスの比率が高い。


# 社会関係
社会関係と一口に言っても、扱う範囲は非常に広い。<br>
ここでは、ニホンザル種内での群れ内の社会関係、群れ間の社会関係、他の動物との種間関係について紹介する。

## 群内の社会関係
ニホンザルはマカク属の中で最も専制的で不寛容である典型的な一種とされる @matsumura1999^,^ @thierry2000^,^ @thierry2007。それはたいていの敵対的交渉は一方方向で、仲直り行動はあまり起こらないためである @chaffin1995^,^ @kutsukake_castles2001^,^ @petit1997^,^ @thierry2008。しかし、ニホンザルには種内変異（intra-species variation）が知られている @inoue-murayama2010^,^ @nakagawa2010^,^ @zhang_watanabe2014。<br>
例えば、小豆島集団では気温の影響を考慮してもサル団子をつくるサルの頭数が高崎山集団より多く、これは他個体に対する寛容性の高さが関わっている可能性を指摘している[@zhang_watanabe2007]。さらに大きなサル団子をつくることができる淡路島集団では、寛容性に関わるとされる紐引き協力実験[@hirata_fuwa2007]を行い、淡路島集団では高い割合で成功したものの勝山集団では低かった[@kaigaishi2019]。

寛容性の指標として使われている行動は、<br>

1. 反撃行動の頻度が高い(＝けんかの頻度そのものは低くはないが、肉体的接触を伴う激しい攻撃は少ない)
1. 仲直り行動の頻度が高い
1. 毛づくろいが近縁個体(or/and)高順位個体に偏らない
1. 子守り行動の頻度が高い
1. コドモの取っ組み合い遊びが長く続く

などが挙げられる @thierry2000^,^ @thierry2008^,^ @matsumura1997^,^ @sterck1997。


### 寛容的社会
<!-- c.f. @nakagawa2013; @nakagawa2010; @nakamichi_yamada2010;@kaigaishi2019 -->


ヤクシマザルの社会は寛容的社会（tolerant society）といわれている理由は、次の４つの事象が挙げられている[@nakagawa2010]。

1. 血縁者による連合の割合が低い[@hanya2008]
1. 末子優位が成り立たない[@hill_okayasu1995]
1. 出生率や毛づくろいの方向性に順位差がない[@hanya2008]
1. 仲直り行動の割合が高い[@hanya2008]

他にも、寛容的社会であるとされる淡路島集団の特徴として、休息時の凝集性の高さがある。この理由として、3者以上からなる毛づくろい交渉と子守り行動の頻度が高いことが指摘されている[@nakamichi_yamada2010]。

<!-- - 仲直り行動 -->
<!-- - 子守り行動 -->
<!-- - 高い凝集性 -->

## 群間の社会関係

### エンカウンター
群れ同士が出会うことをエンカウンター（encounter）という。

屋久島の西部地域海岸部に生息するヤクシマザルは、群れ密度が高く群間関係は敵対的であることが知られている @maruhashi1982^,^ @saito1998^,^ @sugiura2000^,^ @hanya2008。

このことから、他群とのエンカウンターは自分の群れにとって不利な可能性がある。<br>
チンパンジーのようなロングコールや、ネコ科動物のような臭い付け行動など、他群・他個体との接触回避行動がないニホンザルはどうしているのか？<br>
音声プレイバックによる結果、他群の音声に対して、

- 採食をやめ、
- コンタクトコールを減らし、
- 見回し行動を増加

させることで、他群と戦うか逃げるかを判断しているようだ[@kurihara_muto2021]。

### 群れの消失・融合
屋久島では群れが消失し、基本的には一生涯を出自群で過ごすメスでも、別の群れに移籍することが知られている [@takahata1994]。これは群れが遊動域を隣接群から防衛する最小限のサイズがあり、それを下回るとより大きな群れにメスが移籍することが示唆されている。<br>

しかし、実はメスが移籍する前に群れのアルファオスがいなくなっており、このことがメスが他群に移籍した決定打になったかもしれない。

## 種間関係
ヤクシカがヤクシマザルを利用していることの方が多い。

### シカがサルに近づくのはなんで？
ヤクシカはヤクシマザルの糞を食べる [@nishikawa_mochida2010]。<br>
まるでハンバーグを食べるかのようにモグモグと。<br>
だが、しかし、サル糞を食べるかどうかは地域差があるが、なぜそうなのかはわかっていない。<br>

ヤクシカはヤクシマザルの採食に関連する声を聴いて食物の探索効率を上げている可能性がある [@koda2012]。<br>
しかし、日中にシカを個体追跡してみた研究では、採食時間割合は全体の約25%で、そのうちサル関連の採食割合は多くても10%ほどに過ぎなかった @agetsuma_agetsuma2007^,^ @agetsuma_agetsuma2008^,^ @agetsuma_agetsuma2009。<br>

採食割合から見るとシカはサルばかりに頼って食べて生きているわけではないようだ。サル糞の食べ物としての質がどれだけ高いか気になるところだ。

### サルがシカに近づくのはなんで？
ヤクシマザルはヤクシカの背中に乗っていたり、毛づくろいすることがある。<br>
種間交尾行動を目撃したとする事例報告[@pele2017]があるが、この報告を読んでみると実際にはオスザルがメスジカの背中に乗っただけで交尾はしていなかった。
そのため、この行動は種間交尾行動とは言えないだろう。<br>
同種の交尾相手がいないことで発散相手として異種のシカにまたがったとする交尾剝奪（mate deprivation）仮説が挙げられており、この仮説は挙げられた仮説の中で筆者の観察印象に最も近い。ちなみにサルがシカに乗る行動は交尾期に限らず観察できることを注記しておく。

---
サルとシカの種間関係に関する一般向けの本[@tsuji2020]もあるので、興味のある人は読んでみるとよいだろう。


# もっとヤクシマザルを知る
<!-- この章は出来がよさげ -->
論文は、誰でも読めるようにするオープンアクセス化が近年増えてきたが、ハードルが高いと感じる人は多いだろう。そこで、論文以外でヤクシマザルのことについて知ることができる情報をここで整理する。

## ネット教材
**屋久島大学**というオンラインアカデミーで屋久島のことをかなり勉強することができ 、ヤクシマザルについても紹介されている[@univ_yaku]。

## 書籍
屋久島に関わる動植物の研究については多くの書籍が出版されている。以下いくつか紹介。

### ヤクシマザルの書籍
絵本[@yamagiwa_fushihara2020]から一般書[@hanya_matsubara2018]、専門書 @maruhashi1986^,^@takahata_yamagiwa2000 まで幅広い本が刊行されている。

### 屋久島の自然の書籍
ヤクシマザルが生息している自然について知りたいヒトは、植物を中心に屋久島の自然を紹介した本 @yumoto1995^,^@tagawa1994^,^@oosawa_yamagiwa2006 をすすめる。

### サルに関連した民俗学の書籍
現在世界遺産に指定されている西部地域海岸部でのかつての生業について、民俗学者が調査している[@miyamoto1974;@hattori_koizumi2022]。

## 調査ボランティア
毎年夏に**ヤクザル調査隊**という標高1,000m付近でテント泊し、ヤクシマザルの生態調査しているグループがある。調査の際にボランティアを募集しているので、調査体験したい人は参ぜひ加することをおすすめする[@yakuzaruchousatai]。<br>

<!-- ヤクザル調査隊に参加するメリットは多くあるが筆者が得られたものとして次のようなものを経験できたことは大きかった。 -->

<!-- - 野生のサル調査の一端を垣間見れた -->
<!-- - 地図の読み方やロープワークが身につく -->
<!-- - 自分で用意した登山道具は災害でも役に立つ -->

<!-- そしてなにより大きかったのは、<br><br> -->
<!-- **森の中に1人でいるときの解放感と森の一部に過ぎないという感覚**<br><br> -->


ヤクザル調査隊では本[@hanya_matsubara2018]も出ているので、どういうことが行われているのかウェブサイト[@yakuzaruchousatai]以上の情報が気になるヒトは追体験してみるとよいだろう。

## サルの観察
屋久島は世界で唯一世界自然遺産の指定範囲内に生活道路が通っている[@env2019]。そのため、野生のサルを簡単に観察できる世界でも稀有な場所である。
サル観察時の注意事項についてまとめたガイドブックが公開されている[@env2019]。以下の点に注意して観察を楽しもう。

<!-- 1. **サルとの距離感**：サルと10mの距離を保つ -->
<!-- 1. ****：話すときは小声で -->
<!-- 1. **餌付けしない** -->
<!-- 1. **車は歩くスピードで進み続ける** -->


