# 発達
<!-- スプレイグさん、川添さんのD論を参照 -->
ニホンザルの子育てについては日本語の総説がある[@nakamichi2023]。

## アカンボウ期
本土のニホンザルはオスのアカンボウの方がメスよりも母親から離れようとするのが早く、生後1週間ほどで見られる [@hasegawa1983]。

### 子守り行動
アカンボウ期では、子守り行動 (infant handling*)についての研究が多く、母親の子育てスタイル[@sekizawa_kutsukake2019]や子守り行動をする個体の行動パターン[@sekizawa_kutsukake2022;@boyun_furuichi2024]など様々な観点から検討されている。

ヤクシマザルでは、ニホンザルで唯一過度な子守り行動 (excessive infant handling) が確認されている[@boyun_furuichi2024]。詳しくは（*cf.* [社会性](#社会性)）。


*: 用語についてはさまざまあることに注意。

#### アカンボウの顔と子守り行動の関連
ヒトにおいて、未成熟個体の顔の特徴は子守り行動の発現に極めて重要である。この観点からニホンザルを対象にした研究では[@minami_furuichi2024]、ニホンザルでも、広い観点でヒトや大型類人猿での先行研究と一致していて、顔の非線形的な成長曲線はヒトと類似していた。しかし、ヒトとは異なり、アカンボウの顔は母系でも非母系でも子守り行動と相関していなかったうえ、顔の発達変化はアカンボウの行動発達と関連していなかった。これらのことから、アカンボウの顔の多くの特徴は霊長類で共通しているが、ヒトは特有の特徴を選択するように進化した可能性がある。

## コドモ期
３歳を過ぎる頃から、メスは母親と近接する時間が長く、弟や妹の子守り行動が多いがほかのコドモとの遊ぶ時間は減る。一方で、オスのコドモは遊びの時間はあまり変わらず、母親との近接時間が減少し[@mori_naito1986;@nakamichi1989]、群れ周辺にいるオスたちとの交渉をもち始める [@mori_naito1986]。屋久島での発達についての詳しい研究はないが、ほぼ同様の傾向がみられる [@furuichi2000]。

<!--  **＠幸島**:--> 
オスは同年齢のオスとよく近接し、メスは年下個体と交渉している傾向がある[@hayaki1983]。 

## ニホンザルのオスの移出

出自群からの移出である出自分散 (natal dispersal) について金華山と屋久島で比較した研究では [@sprague1998]、平均年齢で屋久島が5.3歳（3.5-10.5歳）、金華山が4.7歳（3-9歳）であった。金華山については別の報告[@sugiura_koyama2002]でも同様の傾向（平均値・中央値ともに５歳、3-9歳）であり、4-6歳で移出する割合が全体の92%を占める。

移出 (dispersal) 
: 群れから出ていくこと。ニホンザルでは、オスが性成熟する前に自分が生まれ育った出自群を出て、メスは基本的に出自群で一生を過ごす @nishida1966^,^ @sugiyama1976^,^ @sprague1998。


### ヤクシマザルのオスの移出

屋久島ではオスの分散は交尾期に集中しており、これは屋久島では群れ同士が隣接しあっているためとされる [@sprague1992]