# もっとヤクシマザルを知る
<!-- この章は出来がよさげ -->
論文は、誰でも読めるようにするオープンアクセス化が近年増えてきたが、ハードルが高いと感じる人は多いだろう。そこで、論文以外でヤクシマザルのことについて知ることができる情報をここで整理する。ニホンザルの最近の知見について知りたい方はこちらの本[@tsuji_nakagawa2017]^,^[@nakagawa_nakamichi_sugiura2010]をお勧めする。

## ネット教材
**屋久島大学**というオンラインアカデミーで屋久島のことをかなり勉強することができ 、ヤクシマザルについても紹介されている[@univ_yaku]。

## 書籍
屋久島に関わる動植物の研究については多くの書籍が出版されている。以下いくつか紹介。

### ヤクシマザルの書籍
絵本[@yamagiwa_fushihara2020]から一般書[@hanya_matsubara2018]、専門書 @maruhashi1986^,^@takahata_yamagiwa2000 まで幅広い本が刊行されている。

### 屋久島の自然の書籍
ヤクシマザルが生息している自然について知りたいヒトは、植物を中心に屋久島の自然を紹介した本 @yumoto1995^,^@tagawa1994^,^@oosawa_yamagiwa2006 をすすめる。

### サルに関連した民俗学の書籍
現在世界遺産に指定されている西部地域海岸部でのかつての生業について、民俗学者が調査している[@miyamoto1974;@hattori_koizumi2022]。

## 調査ボランティア
毎年夏に**ヤクザル調査隊**という標高1,000m付近でテント泊し、ヤクシマザルの生態調査しているグループがある。調査の際にボランティアを募集しているので、調査体験したい人は申し込みして定員オーバーしていなければ参加できる[@yakuzaruchousatai]。<br>

<!-- ヤクザル調査隊に参加するメリットは多くあるが筆者が得られたものとして次のようなものを経験できたことは大きかった。 -->

<!-- - 野生のサル調査の一端を垣間見れた -->
<!-- - 地図の読み方やロープワークが身につく -->
<!-- - 自分で用意した登山道具は災害でも役に立つ -->

<!-- そしてなにより大きかったのは、<br><br> -->
<!-- **森の中に1人でいるときの解放感と森の一部に過ぎないという感覚**<br><br> -->


ヤクザル調査隊では本[@hanya_matsubara2018]も出ているので、どういうことが行われているのかウェブサイト[@yakuzaruchousatai]以上の情報が気になるヒトは追体験してみるとよいだろう。

## サルの観察
屋久島は世界自然遺産の指定範囲内に生活道路が通っており[@env2019]、世界でも珍しい場所である。そのため、野生のサルを簡単に観察できる。
サル観察時の注意事項についてまとめたガイドブックが公開されている[@env2019]。以下の点に注意して観察を楽しもう。

## 屋久島観光一般
National Parks of JapanというYouTubeチャンネルは、自然にやさしく安全に注意しながら楽しむ観光についてわかりやすく紹介している[@MNY]。

<!-- 1. **サルとの距離感**：サルと10mの距離を保つ -->
<!-- 1. ****：話すときは小声で -->
<!-- 1. **餌付けしない** -->
<!-- 1. **車は歩くスピードで進み続ける** -->

