# 群れ
## 分布域・個体数　　
ニホンザル（*Macaca fuscata*）の分布域は、最北を下北半島、南限を屋久島にしている。<br>
現生霊長類で最北限に生息していることで知られている。

### ヤクシマザルの分布・個体数
@hanya2020 , @miyata2017 を参考に情報を整理。

- 1993年、1994年に行われた広域調査では、屋久島全体の25％に当たる海岸から1-2kmの距離にある127km^2^の調査域内に、131群、1984-3850頭が生息していると推定された [@yoshihiro1998]。

そのほかの調査では[@hanya2000]、<br>

- 自然林が最も残っている西部海岸域： 60～100頭/km^2^で、これは野生ニホンザルで最大

- そのほかの海岸域：5～20頭/km^2^、植林による植生の攪乱、捕獲の影響があると考えられる。

- 標高300m以上：20～40頭/km^2^、照葉樹林帯に生息するホンドザルの密度と同程度かむしろ少ない。

### 遊動域
遊動域とは、群れが移動する範囲のことをさす。行動圏ともいう。

- 屋久島低地での群れ遊動域：約数十ヘクタール（約0.2-0.3km^2^）[@kurihara_hanya2015]
- 遊動域の約50％は他群と重複しており [@maruhashi1998]、群れの密度は4.8群/km^2^あるとされる [@yamagiwa_hill1998;@yoshihiro1999]。

- 採食量は均一な森において遊動域($R$)に直接的に比例すると思われるため、群れサイズ($P$)は遊動域に直接的に比例すると思われる。遊動域と群れサイズについて調べた研究では、$R=1.84P$の関係式であらわされた[@maruhashi1982]。

## 群れの構成
複数のオトナのオスと複数のオトナのメス、そのコドモたちからなる**複雄複雌群（multi-male and multi-female groups）**を形成する [@yamagiwa2010]。ニホンザルの社会では、メスは出自の群れで一生を過ごし、オスはほかの群れで過ごすようになる。このような社会は**母系社会（maternal society）**と呼ばれている。オスは3歳頃から他の群れに移籍することが知られ [@sprague1998]、何年かするとまた別の群れに移籍することを繰り返す。<br>

しかし、出自の群れを移籍したオスを死ぬまで追い続けることは非常に難しく、わかっていないことがまだまだ多い。
