# 社会
## そもそも社会とは何か？
動物の社会とは、個体の集合状態に関係なく、様々な行動を介して相互に作用しながら形成される個体間の関係性を指す（例：哺乳類の生物学４　社会）。そのためこの定義に則ると、満員電車の人たちや鴨川で並んで座っている人たちは集まっていても社会を形成しているわけではない。

## 社会構造
ニホンザルのメスは基本的に生まれた群れで生涯を過ごすが、オスは性成熟前後に生まれた群れから移出する（*cf.* [ニホンザルのオスの移出](#ニホンザルのオスの移出)）。そのため、社会構造は母親・姉妹・叔母・姪などの母系の血縁個体集団が核となり、血縁個体と近接や毛づくろいをして一緒に過ごす時間が多い。これはニホンザルに限らず、マカク属全般でも当てはまり、非母系社会をもつ霊長類はむしろ珍しい（例：類人猿）。


# 社会関係
社会関係と一口に言っても、扱う範囲は非常に広い。<br>
ここでは、ニホンザル種内での群れ内の社会関係、群れ間の社会関係、他の動物との種間関係について紹介する。

## 群内の社会関係
霊長類では親密さの指標として毛づくろいや近接などがよく用いられてきた (e.g. 総説 [@ueno2017])。

### 個体間距離
<!-- #### プライベートゾーン -->


#### 凝集性（cohesiveness）
ヤクシマザルは活動項目（activity badget）と社会関係によって個体間距離を変化させている[@nishikawa2014]。活動項目を見ると、毛づくろい・休息時は短く、移動・採食時は長い。一方社会関係では、血縁個体とは音声が聞き取れる範囲内（20m－200m）の距離でつねに維持するが、低順位個体は高順位個体とはあまり近接せず、順位差が開くほど離れている時間が長くなることが知られている。これは食物分布に対応した個体間距離をとり、社会交渉を維持するために個体が集まっていることを示唆する。

### 毛づくろい
#### 毛づくろいの機能
毛づくろいを受けることで

- 外部寄生虫の除去 @tanaka_takefushi1993^,^@zamma2002^,^@onishi2013
- ストレスの減少 @schino1988^,^@aureli1999^,^@ueno2015

があることが報告されている。<br>
一方で、毛づくろいをする個体は

- お返しとして毛づくろいを受けられる[@muroyama1991]
- 第三者との攻撃交渉時の援助 @hemelrijk1994^,^@schino2007

などが報告されています。


### 音声
音声は言語進化の観点から日本の霊長類学黎明期から興味がもたれてきた[@itani1963]。言語進化については他[@nishimura2022]に譲り、ここではニホンザルの音声について紹介する。

#### 音声レパートリー
ニホンザルには、次の音声があることが知られている[@katsu2016]：

- クーコール (coo call)
- ガーニー (girney)
- グラント (grunt)

#### 音声の機能
ヤクシマザルは連続して音声を発する際に、２回目のほうが長めで極めて高頻度で高くなり、２回目の音声の方がよく他個体からの鳴き交わしが起こる[@koda2004]。

屋久島と金華山で比較した研究では、クーコールの頻度が屋久島のほうが高く、屋久島だけコドモよりオトナのほうが頻度が高くなる[@koda2008]。これは生息環境の視界が開けている金華山よりも屋久島のほうが視界が限られているためだと考えられる。

### 社会性
ニホンザルはマカク属の中で最も専制的で不寛容である典型的な一種とされる @matsumura1999^,^ @thierry2000^,^ @thierry2007。それはたいていの敵対的交渉は一方方向で、仲直り行動はあまり起こらないためである @chaffin1995^,^ @kutsukake_castles2001^,^ @petit1997^,^ @thierry2008。しかし、ニホンザルには種内変異（intra-species variation）が知られている @inoue-murayama2010^,^ @nakagawa2010^,^ @zhang_watanabe2014。<br>
例えば、小豆島集団では気温の影響を考慮してもサル団子をつくるサルの頭数が高崎山集団より多く、これは他個体に対する寛容性のちがいが指摘されている[@zhang_watanabe2007]。さらに大きなサル団子をつくることができる淡路島集団では、寛容性に関わるとされる紐引き協力実験[@hirata_fuwa2007]を行い、淡路島集団では高い割合で成功したものの勝山集団では低かった[@kaigaishi2019]。寛容的な社会であるとされる淡路島集団の特徴として、休息時の凝集性の高さがある。この理由として、3者以上からなる毛づくろい交渉と子守り行動の頻度が高いことが指摘されているが[@nakamichi_yamada2010]、寛容性が高いとできるとされる協力行動ができる点が特に顕著である[@kaigaishi2019]。

寛容性の指標として使われている行動は、<br>

1. 反撃行動の頻度が高い(＝けんかの頻度そのものは低くはないが、肉体的接触を伴う激しい攻撃は少ない)
1. 仲直り行動の頻度が高い
1. 毛づくろいが近縁個体(or/and)高順位個体に偏らない
1. 子守り行動の頻度が高い
1. コドモの取っ組み合い遊びが長く続く

などが挙げられる @thierry2000^,^ @thierry2008^,^ @matsumura1997^,^ @sterck1997。



ヤクシマザルの社会は、本土のニホンザルより寛容的な社会（tolerant society）といわれている理由は、次の４つの事象が挙げられている[@nakagawa2010]。

1. 血縁者による連合の割合が低い[@hanya2008]
1. 末子優位が成り立たない[@hill_okayasu1995]
1. 出生率や毛づくろいの方向性に順位差がない[@hanya2008]
1. 仲直り行動の割合が高い[@hanya2008]

これらの他にも、子守り行動（infant handling）においてアカンボウが泣くなどのネガティブな反応を見せてもなお子守行動ができるのは、社会的寛容性が至近要因の一部として働いていることが示唆されている [@boyun_furuichi2024].




## 群間の社会関係

### エンカウンター
群れ同士が出会うことをエンカウンター（encounter）という。

屋久島の西部地域海岸部に生息するヤクシマザルは、群れ密度が高く群間関係は敵対的であることが知られている @maruhashi1982^,^ @saito1998^,^ @sugiura2000^,^ @hanya2008。

このことから、他群とのエンカウンターは自分の群れにとって不利な可能性がある。チンパンジーのようなロングコールや、ネコ科動物のような臭い付け行動など、他群・他個体との接触回避行動がないニホンザルはどうしているのか？音声プレイバックによる結果、他群の音声に対して、採食の停止、コンタクトコールの減少、見回し行動の増加によって、他群と戦うか逃げるかを判断していることが示唆されている[@kurihara_muto2021]。

### 群れの消失・融合
屋久島では群れが消失し、基本的には一生涯を出自群で過ごすメスでも、別の群れに移籍することが知られている [@takahata1994]。これは群れが遊動域を隣接群から防衛する最小限のサイズがあり、それを下回るとより大きな群れにメスが移籍することが示唆されている。<br>

しかし、実はメスが移籍する前に群れのアルファオスがいなくなったと記述されている。メスにとってオスは他群との競合の際の"用心棒"的な役割が指摘されており、自分たちを守ってくれるオスがいなくなったことがメスが他群に移籍した決定打になったかもしれない。

メスがアルファオスを頼りにしている様子は宮城県にある金華山のニホンザルで報告されている @yamaguchi2023a^,^ @yamaguchi2023b。

## 種間関係
ヤクシカがヤクシマザルを利用していることの方が多い。

### シカがサルに近づくのはなんで？
ヤクシカはヤクシマザルの糞を食べる [@nishikawa_mochida2010]。<br>
まるでハンバーグを食べるかのようにモグモグと。<br>
だが、しかし、サル糞を食べるかどうかは地域差があるが、なぜそうなのかはわかっていない。<br>

ヤクシカはヤクシマザルの採食に関連する声を聴いて食物の探索効率を上げている可能性がある [@koda2012]。<br>
しかし、日中にシカを個体追跡してみた研究では、採食時間割合は全体の約25%で、そのうちサル関連の採食割合は多くても10%ほどに過ぎなかった @agetsuma_agetsuma2007^,^ @agetsuma_agetsuma2008^,^ @agetsuma_agetsuma2009。<br>

採食割合から見るとシカはサルばかりに頼って食べて生きているわけではないようだ。サル糞の食べ物としての質がどれだけ高いか気になるところだ。

### サルがシカに近づくのはなんで？
ヤクシマザルはヤクシカの背中に乗っていたり、毛づくろいすることがある。<br>
種間交尾行動を目撃したとする事例報告[@pele2017]があるが、この報告を読んでみると実際にはオスザルがメスジカの背中に乗っただけで交尾はしていなかった。
そのため、この行動は種間交尾行動とは言えないだろう。<br>
同種の交尾相手がいないことで発散相手として異種のシカにまたがったとする交尾剝奪（mate deprivation）仮説が挙げられており、この仮説は挙げられた仮説の中で筆者の観察印象に最も近い。ちなみにサルがシカに乗る行動は交尾期に限らず観察できることを注記しておく。

---
サルとシカの種間関係に関する一般向けの本[@tsuji2020]もあるので、興味のある人は読んでみるとよいだろう。

