# 体温調節
ヒトの日常生活では、服の脱ぎ着、窓の開け閉め、うちわ・扇風機・エアコンなどを使って体温調節する。そのような工夫ができない野生動物はどのように体温調節しているのだろうか。

ニホンザルは現生霊長類の中で最北端に生息する種であり[@fooden1982] 、霊長類の中で最も高い体毛密度がみられる[@inagaki1992]。 これは寒冷地に適応した形質と考えられる [@inagaki_hamada1985]。そのような観点から寒さ対策の研究が多くなされてきた。

ーーーーー


動物の体温調節研究について知りたい人は哺乳類[@terrien2011] ・霊長類[@thompson_hermann2024] のレビュー論文に当たられたい。


キーワード：体温調節；温熱生物学；温度生物学<br>
key words: Thermoregulation; Thermal biology 


 

行動性体温調節
: 気温や体温と関連している行動を一般に**行動性体温調節（behavioral thermoregulation）**と呼ぶ。行動性体温調節と似たような用語で**体温調節行動（thermoregulatory behavior）**があるが、これは具体的な行動を指す場合（例：日向・日陰利用、サル団子）に用いられる。混同しないように注意されたい。

それでは、具体的な体温調節行動を見ていこう。

## サル団子
ニホンザルでは非常に多くのサル団子（huddling）の研究がある。 [@takahashi1997; @hanya2007; @zhang_watanabe2007; @wada2007; @ueno_nakamichi2016; @ueno_nakamichi2018; @ishizuka2021; @herbrich2024; @sueur2024]


### 社会性
サル団子は他個体と寄り集まり接触することから社会的体温調節（social thermoregulation）とも呼ばれている。例えば、金華山島ではサル団子の時にしか接触しない個体がいることがわかっており、社会的寛容性が高まっていることが示唆されている [@takahashi1997]。社会的寛容性には地域差があることが、小豆島と高崎山のサル団子の集団サイズの違いから報告されている [@zhang_watanabe2007]。

## 温泉浴
地獄谷のニホンザルが温泉に入ることは世界的に有名である。冬によく温泉浴することから、体温調節との関連が示唆され [@zhang2007; @takeshita2018]、ストレス指標として糞中グルココルチコイド濃度を測定した研究では、温泉浴には秋には違いが見られなかったものの、冬にストレス軽減の効果があることが明らかとなっている [@takeshita2018]。

## 日照利用
非常に多くの動物種で日向・日陰の日照利用による体温調節の研究がなされているが、ニホンザルを対象とした研究は、屋久島で日光浴の研究 [@hanya2007] がある程度で、意外と少ない。

ニホンザルを対象とした研究の大半は、ニホンザルが寒冷地に適応した種ということもあってか、冬に調査されてきた。そのため、ニホンザルがどのような暑さ対策をしているのかほとんどわかっていなかった。また哺乳類一般に、寒いときより。暑いときの体温調節行動の数は限られており、そのうえ、湿度の効果は十分に理解されていなかった。

そのような背景の中、休息場所を日向・日陰・半日陰の3つに分け、ヤクシマザルがどのような気温・湿度の時に休息場所（微小生息地、microhabitat）を選択しているのかを調べた研究では、約22°C以上の高温下で湿度によって休息場所を選択していることが明らかとなった [@tabuse2026]。具体的には、湿度60％以下の乾燥時には半日陰を、湿度80％以上の湿潤時には日陰を選択していることが明らかとなった。この研究によって内温動物全般を見渡しても検討されてこなかった半日陰の体温調節的意義が解明され、今後どのような動物種で半日陰利用が見られるのか検証されることが期待されている。



