# ニホンザルのトリビア
ここではニホンザルの話題を紹介する。

## ニホンザルの学名
>ニホンザルの学名は元々"*Macaca speciosa*"であった[@iwamoto1985]

"*Macaca speciosa*"は1826年に記載され[@geoffroy1826]、"*Macaca fuscata*"の記載[@blyth1875]より古い。しかし誤ってベニガオザルに使われてきた歴史が長く、現在は混乱を防ぐため両者ともに使われていない。*Macaca speciosa*の種名は「目立つ、すばらしい」という意味だが、*Macaca fuscata*は対照的に「暗色がかった」という意味。命名する学者によって印象がだいぶ違うらしい・・・。<br>
ちなみにベニガオザルの学名は*Macaca arctoides*、「クマのような」の意味。


## ヤクシマザルのお隣さん
>屋久島の隣島である種子島のニホンザルは大正時代以降に絶滅している[@azuma_yoshiba1972; @santo1989]

1923年（大正12年）に種子島にニホンザルがいたことが、当時東北帝国大学教授であった長谷川言人による全国アンケートによって明らかになっている。屋久島と種子島は約20kmしか離れておらず、同じ亜熱帯地域であるため気温はほぼ同程度の傾向でありながら降水量が大きく異なり、林芙美子の小説『浮雲』[@hayashi_ukigumo]には「月に三十五日も雨が降る」と表現されるほどである（図 \@ref(fig:TaneYakuClimate), c.f. [気象庁の観測データ](https://www.data.jma.go.jp/gmd/risk/obsdl/)）。このような生態学的観点から、霊長類学が始まる戦後も種子島のニホンザルが生き残っていれば、屋久島と種子島での比較研究は興味深かっただろう。

```{r, TaneYakuClimate, message=FALSE, warning=FALSE, echo=FALSE, fig.cap="屋久島と種子島の気象データの比較<br>公開されている気象庁の過去の観測データからダウンロードし分析した。分析データは、屋久島観測所（＠屋久島町小瀬田）と種子島観測所（＠西之表市西之表）のデータ、2020年から2022年までの3年間のデータを用いた。"}
library(tidyverse)


y1.lim <- c(0,35) #左軸気温
y2.lim <- c(0,3500) #右軸降水量

scaler <- (y2.lim[2] - y2.lim[1])/(y1.lim[2] - y1.lim[1])


read_csv("data/taneyaku_climate20_22.csv", skip = 6) %>% 
  drop_na() %>% 
  group_by(site, month) %>% 
  summarise("temp_max_month" = max(temp_max),
            "temp_mean_month" = mean(temp_mean),
            "temp_min_month" = min(temp_min),
            "rainfall_month" = sum(rainfall)/3,
            "wind_speed_month" = mean(wind_speed)) %>%
  pivot_longer(cols = temp_max_month:temp_min_month, 
               names_to = "temp_type", 
               values_to = "temp_month") %>% 
  mutate(site = str_replace_all(site, c("tane" = "種子島", "yaku" = "屋久島"))) %>% 
  ggplot() +
  facet_grid(~ site) +
  geom_bar(aes(x = month, y = rainfall_month), 
           stat = 'identity', fill = "grey60", 
           width = 0.7,
           breaks = seq(0,3500,500)) +
  geom_line(aes(x = month, y = temp_month*scaler, color = temp_type), size = 1) +
  scale_color_hue(name = "", labels = c(temp_max_month = "月最高気温", 
                                        temp_mean_month = "月平均気温", 
                                        temp_min_month = "月最低気温")) + 
  scale_x_continuous(breaks = seq(1,12,1)) +
  scale_y_continuous(limit = y2.lim, 
                     expand = c(0, 0), 
                     sec.axis=sec_axis(trans = ~ ./scaler, 
                     breaks = seq(y1.lim[1],y1.lim[2],5), 
                     name="気温 (°C)")) +
  labs(x = "月（2020年から2022年までの3年間の平均値）",
       y = "降水量 (mm)") +
  theme_bw(base_size = 16)+
  theme(axis.title.y = element_text(family = "Arial", size = 14.5),
        axis.text.x = element_text(family="Arial",
                                   face = "bold", size = 10.5),
        axis.title = element_text(family = "Yu Gothic",
                                  size = 20),
        legend.text = element_text(family = "Yu Gothic"),
        axis.text.y = element_text(family ="Arial"),
        plot.caption = element_text(family = "Yu Gothic")) 




```

## 日本の動物園で見られるヤクシマザル
>ヤクシマザルは平川動物公園（鹿児島市）と沖縄こどもの国（沖縄市）、日本モンキーセンター（犬山市）の3施設で飼育されている

日本動物園水族館協会の[ウェブサイト](https://www.jaza.jp/animal/search?_method=true&page=45)によると、2024年1月現在、平川動物公園（鹿児島市）と沖縄こどもの国（沖縄市）でヤクシマザルが飼育されている。日本モンキーセンター（JMC）でも飼育されており、JMCのサルは焚火に当たることで有名。

ちなみに亜種名がホンドザルとなるニホンザルは <br>
**北海道**<br>
円山動物園（札幌市）、旭山動物園（旭川市）、おびひろ動物園（帯広市）、釧路市動物園（釧路市）

**東北地方**<br>
弥生いこいの広場（弘前市）

**関東甲信越地方**<br>
宇都宮動物園（宇都宮市）、大宮公園（さいたま市）、東武動物公園（宮代町）、狭山智光山動物園（埼玉県狭山市）、上野動物園（台東区）、羽村市動物公園（東京都羽村市）、市原ぞうの国（市原市）、小諸動物園（長野県小諸市）、須坂市動物園（長野県須坂市）、茶臼山動物園（長野市）

**東海・北陸地方**<br>
高岡古城公園動物園（富山県高岡市）、楽寿園（静岡県三島市）、日本平動物園（静岡市）、岡崎動物園（愛知県岡崎市）

**関西地方**<br>
姫路セントラルパーク（兵庫県姫路市）

**中国・四国地方**<br>
とくしま動物園（徳島市）、とべ動物園（愛媛県砥部町）、池田動物園（岡山市）、福山動物園（広島県福山市）、徳山動物園（山口県周南市）

**九州・沖縄地方**<br>
到津の森公園（福岡県北九州市）、九十九島動植物園（長崎県佐世保市）、熊本市動植物園（熊本市）、フェニックス動物園（宮崎市）

以上29施設で飼育されている。
