
# ニホンザルの体のふしぎ
ニホンザルには、ヒトにはない体の特徴がみられる。<br>
これらの特徴はニホンザルにとってどのような生物学的意義があるのだろうか。




<!-- ## 拇指対向性 -->

## 口周りが大きくなる理由
ニホンザルを見ると口の両脇が大きく膨らんでいることがある。

これはニホンザルには「**頬袋**」があるためである [@maruhashi1993]。<br>
この頬袋に木の実を一時的に詰め込めるおかげで、木から降りて移動や毛づくろいをしながら木の実を食べることができる。<br>
ニホンザルの仲間であるオナガザル上科のサル（旧称：旧世界ザル）は、オマキザル上科のサル（旧称：新世界ザル）や類人猿とはちがい、頬袋をもっている。

この頬袋があることで種子散布の距離が変わるため [@yumoto1998]、植物にとっても無視できない重要な部位である。
例えば、ヤマモモの主要な種子散布者であるニホンザルが生息する屋久島と絶滅した種子島で比較した研究では、種子島の方が種子散布距離が短く、近縁個体が集中していることが明らかとなっており、種子島のヤマモモの世代更新に負の影響の可能性が指摘されている [@watanabe2026]。

---

新世界ザル、旧世界ザルという呼び名は植民地的なニュアンスがあることから今は使わないことが推奨されている。例えば、国際霊長類学会の公式学術雑誌である*International Journal of Primatology*誌の論文投稿規定[@IJP_guidelines]（submission guidelines）では以下のように記述されている。

> "Avoid the terms New World and Old World, which have colonial overtones. Use formal taxonomic terms (e.g., platyrrhine, catarrhine), American and Afro-Eurasian monkeys, or other appropriate terms"


Natureに掲載されたコラム[@adame2023]や他の霊長類学雑誌に掲載された論文[@bezanson2024]でも同様の議論がなされている。


<!-- 頬袋は未熟果消化のために発達したのか？ -->
<!-- 未熟果を嘔吐せずに採食するため？？ -->


<!-- 系統樹を入れる -->

## お尻にあるコブは何？
ニホンザルのお尻にある白いものはニンニクではない。

これは「**尻ダコ**」と呼ばれる突起物である。<br>
尻ダコは、オナガザル科と類人猿のテナガザル科の霊長類の坐骨結節に付着し，坐ることへの適応を高めていると考えられている [@washburn1957]。<br>
オナガザル科に属するニホンザルは、この尻ダコをクッションとして使えるおかげで、長いこと座ることができる。


## 顔やお尻が赤い理由
ニホンザルの顔が赤いのは怒っているからではない。<br>顔やお尻が赤くなるのは性ホルモンが影響しており、性成熟した証である。

ニホンザル同様、雌雄いずれも顔・外陰部・臀部が赤くなるアカゲザル（*Macaca mulatta*）で色彩の研究が多く、その機能が一部明らかになっている。<br>メスの性皮の赤さは排卵期頃に濃くなり[@dubuc2009; @higham2010; @higham2011]、オスの場合は交尾期に濃くなる[@baulu1976; @higham2013]。しかし色彩の程度には大きな個体差がある。
一方、オスの性皮の色彩はテストステロン（オスの主要な性ホルモン）によって制御されている。テストステロンはエストロゲン依存性受容体に作用し、表皮の血流量が増減することで顔の赤さが決まる[@baulu1976; @rhodes1997]。

<!-- # ヤクシマザルのふしぎ -->
<!-- ## 他の地域のニホンザルより体が小さいのはなんで？ -->
<!-- 身体が小さい理由は明らかにされていないが、仮説は二つある。 -->

<!-- 1. **島嶼効果（とうしょこうか）** -->
<!-- 2. **ベルクマンの法則** -->

<!-- 島嶼効果が働いている可能性がある。島嶼効果は俗にフォスターの法則とも呼ばれている。 -->


<!-- ## 尻尾が短いのはなぜ？ -->



